import { Video, Playlist, Section, VideoSection } from './types';
import { formatDuration } from './formatters';

export const INITIAL_SECTIONS: Section[] = [
  {
    id: 'movies',
    name: 'Movies',
    slug: 'movies',
    description: 'Blockbuster cinematic feature films, animation, and narrative cinema.',
    icon: 'Film',
    color: '#E50914',
    status: 'enabled',
    display_order: 1,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sports',
    name: 'Sports',
    slug: 'sports',
    description: 'Thrilling tournament highlights, athletic competitions, and extreme action.',
    icon: 'Trophy',
    color: '#00C49F',
    status: 'enabled',
    display_order: 2,
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'entertainment',
    name: 'Entertainment',
    slug: 'entertainment',
    description: 'Creative specials, cultural shows, and entertainment productions.',
    icon: 'Sparkles',
    color: '#8884D8',
    status: 'enabled',
    display_order: 3,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'music',
    name: 'Music',
    slug: 'music',
    description: 'Concert streams, studio performances, and original sound recordings.',
    icon: 'Music',
    color: '#FFBB28',
    status: 'enabled',
    display_order: 4,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'gaming',
    name: 'Gaming',
    slug: 'gaming',
    description: 'Esports matches, speedruns, game reviews, and live streams.',
    icon: 'Gamepad2',
    color: '#FF8042',
    status: 'enabled',
    display_order: 5,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'documentary',
    name: 'Documentary',
    slug: 'documentary',
    description: 'Expeditions, nature investigations, and deep dive documentaries.',
    icon: 'Compass',
    color: '#0088FE',
    status: 'enabled',
    display_order: 6,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_VIDEOS: Video[] = [
  {
    id: 'big-buck-bunny',
    title: 'Big Buck Bunny (Official 4K Master)',
    description: 'A large and lovable rabbit deals with bullying forest creatures in this renowned open-source animated short created by the Blender Foundation.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80',
    videoUrl: 'https://archive.org/download/BigBuckBunny_124/Content/big_buck_bunny_720p_surround.mp4',
    sourceType: 'direct',
    duration_seconds: 596,
    duration: 596,
    duration_formatted: formatDuration(596),
    visibility: 'public',
    status: 'published',
    playlistId: 'blender-open-movies',
    sectionIds: ['movies', 'entertainment'],
    views: 1420,
    tags: ['Animation', 'Comedy', 'Open Source'],
    category: 'Animation',
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    uploadedBy: 'Admin',
  },
  {
    id: 'tears-of-steel',
    title: 'Tears of Steel (Sci-Fi VFX Feature)',
    description: 'Set in a dystopian future in Amsterdam, a group of scientists and soldiers attempt to stage a crucial event to save mankind from destructive cyber robots.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    videoUrl: 'https://archive.org/download/Tears-of-Steel/tears_of_steel_720p.mp4',
    sourceType: 'direct',
    duration_seconds: 734,
    duration: 734,
    duration_formatted: formatDuration(734),
    visibility: 'public',
    status: 'published',
    playlistId: 'blender-open-movies',
    sectionIds: ['movies', 'entertainment'],
    views: 890,
    tags: ['Sci-Fi', 'VFX', 'Action'],
    category: 'Sci-Fi',
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    uploadedBy: 'Admin',
  },
  {
    id: 'sintel-fantasy-quest',
    title: 'Sintel (The Dragon Quest)',
    description: 'A lonely young woman searches through a mountainous wilderness and dangerous ruins to find her kidnapped companion, a young dragon named Scales.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=800&auto=format&fit=crop&q=80',
    videoUrl: 'https://archive.org/download/Sintel/sintel-2048-surround.mp4',
    sourceType: 'direct',
    duration_seconds: 888,
    duration: 888,
    duration_formatted: formatDuration(888),
    visibility: 'public',
    status: 'published',
    playlistId: 'blender-open-movies',
    sectionIds: ['movies', 'entertainment'],
    views: 2150,
    tags: ['Fantasy', 'Adventure', 'Drama'],
    category: 'Fantasy',
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    uploadedBy: 'Admin',
  },
  {
    id: 'elephants-dream',
    title: 'Elephants Dream (Surrealist Sci-Fi)',
    description: 'Two men explore the bizarre, infinitely complex interior machinery of an enigmatic machine that shifts and responds to their thoughts.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80',
    videoUrl: 'https://archive.org/download/ElephantsDream/ed_1024_512kb.mp4',
    sourceType: 'direct',
    duration_seconds: 653,
    duration: 653,
    duration_formatted: formatDuration(653),
    visibility: 'public',
    status: 'published',
    playlistId: 'blender-open-movies',
    sectionIds: ['movies'],
    views: 640,
    tags: ['Surreal', '3D', 'Sci-Fi'],
    category: 'Animation',
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    uploadedBy: 'Admin',
  },
  {
    id: 'hls-adaptive-demo',
    title: 'Adaptive Multi-Bitrate HLS Stream Demo',
    description: 'Ultra-low latency HTTP Live Streaming (.m3u8) video stream demonstrating dynamic multi-resolution bitrate switching.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&auto=format&fit=crop&q=80',
    videoUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    sourceType: 'hls',
    duration_seconds: 634,
    duration: 634,
    duration_formatted: formatDuration(634),
    visibility: 'public',
    status: 'published',
    playlistId: 'streaming-tech',
    sectionIds: ['gaming', 'entertainment'],
    views: 310,
    tags: ['HLS', 'LiveStreaming', 'Tech'],
    category: 'Technology',
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    uploadedBy: 'Admin',
  },
  {
    id: 'for-bigger-blazes',
    title: 'Oceans (Cinematic 4K Nature Feature)',
    description: 'High dynamic range wildlife cinematography exploring the deep marine ecosystems of our oceans.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1498855926480-d98e83099315?w=800&auto=format&fit=crop&q=80',
    videoUrl: 'https://vjs.zencdn.net/v/oceans.mp4',
    sourceType: 'direct',
    duration_seconds: 47,
    duration: 47,
    duration_formatted: formatDuration(47),
    visibility: 'public',
    status: 'published',
    playlistId: 'streaming-tech',
    sectionIds: ['documentary', 'sports'],
    views: 470,
    tags: ['Nature', 'Cinematography', 'Ocean'],
    category: 'Nature',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    uploadedBy: 'Admin',
  },
];

export const INITIAL_VIDEO_SECTIONS: VideoSection[] = [
  { id: 'big-buck-bunny_movies', video_id: 'big-buck-bunny', section_id: 'movies', created_at: new Date().toISOString() },
  { id: 'big-buck-bunny_entertainment', video_id: 'big-buck-bunny', section_id: 'entertainment', created_at: new Date().toISOString() },
  { id: 'tears-of-steel_movies', video_id: 'tears-of-steel', section_id: 'movies', created_at: new Date().toISOString() },
  { id: 'tears-of-steel_entertainment', video_id: 'tears-of-steel', section_id: 'entertainment', created_at: new Date().toISOString() },
  { id: 'sintel-fantasy-quest_movies', video_id: 'sintel-fantasy-quest', section_id: 'movies', created_at: new Date().toISOString() },
  { id: 'sintel-fantasy-quest_entertainment', video_id: 'sintel-fantasy-quest', section_id: 'entertainment', created_at: new Date().toISOString() },
  { id: 'elephants-dream_movies', video_id: 'elephants-dream', section_id: 'movies', created_at: new Date().toISOString() },
  { id: 'hls-adaptive-demo_gaming', video_id: 'hls-adaptive-demo', section_id: 'gaming', created_at: new Date().toISOString() },
  { id: 'hls-adaptive-demo_entertainment', video_id: 'hls-adaptive-demo', section_id: 'entertainment', created_at: new Date().toISOString() },
  { id: 'for-bigger-blazes_documentary', video_id: 'for-bigger-blazes', section_id: 'documentary', created_at: new Date().toISOString() },
  { id: 'for-bigger-blazes_sports', video_id: 'for-bigger-blazes', section_id: 'sports', created_at: new Date().toISOString() },
];

export const INITIAL_PLAYLISTS: Playlist[] = [
  {
    id: 'blender-open-movies',
    title: 'Blender Open Movies Anthology',
    description: 'A curated collection of open-source computer-animated short films produced by the Blender Animation Studio.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80',
    videoIds: ['big-buck-bunny', 'tears-of-steel', 'sintel-fantasy-quest', 'elephants-dream'],
    status: 'published',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'Admin',
  },
  {
    id: 'streaming-tech',
    title: 'Streaming Technology & Demos',
    description: 'Adaptive HLS and direct video streaming test streams for checking multi-bitrate delivery and responsive buffering.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&auto=format&fit=crop&q=80',
    videoIds: ['hls-adaptive-demo', 'for-bigger-blazes'],
    status: 'published',
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'Admin',
  },
];
